### ISSUE TITLE
Where to download prebuilt binary?

### ISSUE THREAD

**Issue by 3oheicrw** [getskye/browser#2]
Someone on the wexond browser repo suggested me this browser but the only thing I can see is source code but no prebuilt binary. So how to use it? I don't want to have to build from source.

The website https://getskye.app/ can't be opened because of this error:

Error 1000 Ray ID: 6f90fa860f8e18a8 • 2022-04-09 05:52:47 UTC
DNS points to prohibited IP
What happened?

You've requested a page on a website (getskye.app) that is on the Cloudflare network. Unfortunately, it is resolving to an IP address that is creating a conflict within Cloudflare's system.
What can I do?

If you are the owner of this website:
you should login to Cloudflare and change the DNS A records for getskye.app to resolve to a different IP address.

Well, this clearly is a bad configuration of your side.

**Comment by A-da-m** [comment]
This repo is still a work in progress, the current stable repo can be found here https://github.com/skyebrowser/skye
